runtime: php55
api_version: 2

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
  
-url: /scripts
static_dir:scripts
	
-url: /css
static_dir:css

# Serve php scripts.
- url: /.*
  script: index.php
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico