runtime: php55
api_version: 1
service: default

inbound_services:
  - mail
  - warmup


handlers:
# Serve images as static resources.

- url: /script/.+
  script: email.php
  login: admin
- url: /css
  static_dir: css
- url: /script/
  script: /email.php
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /less
  static_dir: less
- url: /mail
  script: /mail/contact_me.php
- url: /vendor
  static_dir: vendor
- url: /db/
  script: /db.php
- url: /admin/links
  script: /admin/index.php
- url: /admin/links/add
  script: /admin/add.php

# Serve php scripts.
- url: /
  script: index.php
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
# [START env]
env_variables:
  # Replace project, instance, database, user and password with the values obtained
  # when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/homepagematt:us-central1:homepage;dbname=homepage
  MYSQL_USER: root
  MYSQL_PASSWORD: ''
# [END env]