runtime: php55
api_version: 1
service: default

inbound_services:
  - mail
  - warmup


handlers:
# Serve images as static resources.

- url: /script/.+
  script: email.php
  login: admin
- url: /css
  static_dir: css
- url: /script/
  script: /email.php
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /less
  static_dir: less
- url: /mail
  static_dir: mail
- url: /vendor
  static_dir: vendor
- url: /db/
  script: /db.php
  

# Serve php scripts.
- url: /.*
  script: index.php
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico